#!/usr/bin/env bash
autorandr -c

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$HOME"/.config/leftwm/themes/current/down /tmp/leftwm-theme-down

# Set the theme.toml config
echo "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$HOME"/.config/leftwm/themes/current/assets/background.jpg
fi

dunst -conf "$HOME"/.config/dunst/dunstrc &
blueman-applet &
nm-applet &
xss-lock slock &

index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$HOME"/.config/leftwm/themes/current/liquid/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$HOME"/.config/polybar/config $barname &> /dev/null &
  let index=index+1
done
