#!/usr/bin/env bash

##This script assigns a default application to each Tag (1-9), and opens the application assigned to the currently focused tag when run.
##Please copy misc/default_apps.sh to your root leftwm config folder ($HOME/.config/leftwm) and configure your preferred defaults there.

#Imports variables from default_apps.sh, or assigns default variables if default_apps.sh does not exist.
if test -e "$HOME"/.config/leftwm/default-apps.sh;
then
  source $HOME/.config/leftwm/default-apps.sh;
else
  export TERM=alacritty
  export BROWSER=firefox
  export DOC=libreoffice
  export FILE=dolphin
  export PLAYER=celluloid
  export GAME=steam
  export PHOTO=gimp
  export SANDBOX=virtualbox
  export DEV="alacritty -e vim";
fi

#Lookup Focused tag
TAG=$(leftwm-state -q -w 0 -t "$HOME"/.config/leftwm/themes/current/name.liquid)

#Executes application based on number of focused tag
case "$TAG" in 
  1) $TERM &> /dev/null ;;
  2) $BROWSER &> /dev/null ;;
  3) $DOC &> /dev/null ;;
  4) $FILE &> /dev/null ;;
  5) $PLAYER &> /dev/null ;;
  6) $GAME &> /dev/null ;;
  7) $PHOTO &> /dev/null ;;
  8) $SANDBOX &> /dev/null ;;
  9) $DEV &> /dev/null ;;
esac
