#!/usr/bin/env bash

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$HOME"/.config/leftwm/theme/current/down.jpg
fi

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

pkill compton
pkill picom
pkill polybar
pkill dunst
pkill xss-lock
