#!/usr/bin/env bash

# OS
os=$(hostnamectl | grep 'Operating System: ')
os=$(echo $os | sed -e s/^"Operating System: "//)
os=$(echo $os | sed -e s/" Linux"//)
echo "os:$os"

# Kernel
kernel=$(hostnamectl | grep 'Kernel: ')
kernel=$(echo $kernel | sed -e s/^"Kernel: Linux "//)
echo "kernel:$kernel"

# WM
wm=$(wmctrl -m | grep 'Name:')
wm=$(echo $wm | sed -e s/^"Name: "//)
echo "wm:$wm"

# Packages
nixpkgs=$(nix-store --query --requisites /run/current-system | cut -d- -f2- | sort | uniq | wc -l)
echo "pkg:$nixpkgs"

# uptime
up=$(uptime -p)
up=$(echo $up | sed -e s/^"up "//g)
up=$(echo $up | sed -e s/" day"/"d"/g)
up=$(echo $up | sed -e s/" hour"/"h"/g)
up=$(echo $up | sed -e s/" minute"/"m"/g)
up=$(echo $up | sed -e s/","//g)
up=$(echo $up | sed -e s/"s"//g)
echo "up:$up"

#cpu
cpu=$(cat /proc/cpuinfo | grep 'model name' -m 1)
cpu=$(echo $cpu | sed -e s/^"model name : "//)
echo "cpu:$cpu"

# shell
shell=$(echo $SHELL | sed -e s:/usr/bin/::)
echo "shell:$shell"
