#!/usr/bin/env bash

# Outputs a random title from a list of titles

titles=(
  "Mechromancer"
  "Linux Enthusiast"
  "Functional Madness"
  "Terminal Dweller"
)

rand=$[$RANDOM % ${#titles[@]}]
echo ${titles[$rand]}

