# Abbreviations:
abbr --add --global -- g 'git'
abbr --add --global -- ga 'git add'
abbr --add --global -- gbl 'git blame'
abbr --add --global -- gcm 'git commit -m'
abbr --add --global -- gca 'git commit --amend'
abbr --add --global -- gcf 'git commit --fixup'
abbr --add --global -- gcl 'git clone'
abbr --add --global -- gco 'git checkout'
abbr --add --global -- gf 'git fetch'
abbr --add --global -- gl 'git log --graph --pretty "format:%C(yellow)%h%Creset %C(red)%G?%Creset%C(green)%d%Creset %s %Cblue(%cr) %C(bold blue)<%aN>%Creset"'
abbr --add --global -- gll 'git log --pretty "format:%C(yellow)%h%Creset %C(red)%G?%Creset%C(green)%d%Creset %s %Cblue(%cr) %C(bold blue)<%aN>%Creset"'
abbr --add --global -- gop 'git open'
abbr --add --global -- gp 'git push'
abbr --add --global -- gpl 'git pull --rebase --autostash'
abbr --add --global -- gr 'git reset HEAD'
abbr --add --global -- gs 'git status --short .'
abbr --add --global -- gss 'git status'
abbr --add --global -- gst 'git stash'
abbr --add --global -- gv 'git rev-parse'
