# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nx-dark-reader = {
    pname = "nx-dark-reader";
    version = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-dark-reader";
      rev = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
      fetchSubmodules = false;
      sha256 = "sha256-CKJGCk7ATd0naFhill5rrvay6V2JE4Bstu4tFpaAjB0=";
    };
    date = "2023-06-20";
  };
  nx-search-engines = {
    pname = "nx-search-engines";
    version = "f81f47df82f8e322f0a8919d05fc513297095a0b";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-search-engines";
      rev = "f81f47df82f8e322f0a8919d05fc513297095a0b";
      fetchSubmodules = false;
      sha256 = "sha256-Q+6B3lDzlhfHnS306yLh5LpxdIXESdH/Y2D3GJodbXs=";
    };
    date = "2023-06-07";
  };
  pantalaimon = {
    pname = "pantalaimon";
    version = "33909aa2514dc5e9108e149c08a617f5149e52d4";
    src = fetchFromGitHub {
      owner = "matrix-org";
      repo = "pantalaimon";
      rev = "33909aa2514dc5e9108e149c08a617f5149e52d4";
      fetchSubmodules = false;
      sha256 = "sha256-ck0cTSGgN0qBY1uyDqU+1CpPPntMAVhSpfGzrBlA61c=";
    };
    date = "2024-10-07";
  };
  telega = {
    pname = "telega";
    version = "aa891d2a5a6cba18ab79b42d396795f7b61f2e9f";
    src = fetchFromGitHub {
      owner = "zevlg";
      repo = "telega.el";
      rev = "aa891d2a5a6cba18ab79b42d396795f7b61f2e9f";
      fetchSubmodules = false;
      sha256 = "sha256-V4oqnCTFYynz5h3rlWzx2MfHhEBox4am0zLvRYRWKhM=";
    };
    date = "2024-09-11";
  };
}
