# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nx-dark-reader = {
    pname = "nx-dark-reader";
    version = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-dark-reader";
      rev = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
      fetchSubmodules = false;
      sha256 = "sha256-CKJGCk7ATd0naFhill5rrvay6V2JE4Bstu4tFpaAjB0=";
    };
    date = "2023-06-20";
  };
  nx-search-engines = {
    pname = "nx-search-engines";
    version = "f81f47df82f8e322f0a8919d05fc513297095a0b";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-search-engines";
      rev = "f81f47df82f8e322f0a8919d05fc513297095a0b";
      fetchSubmodules = false;
      sha256 = "sha256-Q+6B3lDzlhfHnS306yLh5LpxdIXESdH/Y2D3GJodbXs=";
    };
    date = "2023-06-07";
  };
  pantalaimon = {
    pname = "pantalaimon";
    version = "a15f3e49c3672741f16ded2eccab55297ccd43c4";
    src = fetchFromGitHub {
      owner = "matrix-org";
      repo = "pantalaimon";
      rev = "a15f3e49c3672741f16ded2eccab55297ccd43c4";
      fetchSubmodules = false;
      sha256 = "sha256-wQFK0o8W1K0QaKz3fqPn3YC2Fg6/+gNXh2AMepbhQm8=";
    };
    date = "2024-11-01";
  };
  telega = {
    pname = "telega";
    version = "3836cff15393fe1dc1addb4fe46b11878dab4891";
    src = fetchFromGitHub {
      owner = "zevlg";
      repo = "telega.el";
      rev = "3836cff15393fe1dc1addb4fe46b11878dab4891";
      fetchSubmodules = false;
      sha256 = "sha256-50giikYe+YvC74BOy2sW+0EMkycllPHNOmvNbJiGw5E=";
    };
    date = "2024-12-20";
  };
}
