[pantalaimon]
src.git = "https://github.com/matrix-org/pantalaimon.git"
src.branch = "fix-dbus"
fetch.github = "matrix-org/pantalaimon"

[telega]
src.git = "https://github.com/zevlg/telega.el.git"
fetch.github = "zevlg/telega.el"

# :NOTE| Nyxt-related
[nx-dark-reader]
src.git = "https://github.com/aartaka/nx-dark-reader.git"
fetch.github = "aartaka/nx-dark-reader"

[nx-search-engines]
src.git = "https://github.com/aartaka/nx-search-engines.git"
fetch.github = "aartaka/nx-search-engines"
